Repository broadinstitute/single_cell_portal_core, pull requests merged in 2020-01, with the labels that each got.

#346 Sl update baseimage 2019-12-18 (SCP-2041)
  .travis.yml
  Dockerfile
  Gemfile
  Gemfile.lock
  README.md
Labels: security-risk: low

#348 Updating parse completion/failure email contents
  app/mailers/single_cell_mailer.rb
  app/models/admin_configuration.rb
  app/models/cluster_group.rb
  app/models/ingest_job.rb
  app/models/study.rb
  app/views/devise/sessions/new.html.erb
  app/views/single_cell_mailer/notify_user_parse_complete.html.erb
  app/views/single_cell_mailer/notify_user_parse_complete.text.erb
  app/views/single_cell_mailer/notify_user_parse_fail.html.erb
  app/views/single_cell_mailer/notify_user_parse_fail.text.erb
Labels: security-risk: low

#350 Upload Wizard updates, yarn compilation
  .travis.yml
  app/views/studies/_metadata_convention_help_popover.html.erb
  app/views/studies/_sort_warning.html.erb
  app/views/studies/initialize_study.html.erb
  rails_startup.bash
  yarn.lock
Labels: dependencies, security-risk: low

#351 Gating subsampling, adding cleanup
  app/models/cluster_group.rb
  app/models/delete_queue_job.rb
  app/models/ingest_job.rb
  db/migrate/20200103191405_set_subsampled_on_clusters.rb
Labels: security-risk: low

#354 Limiting gene search to 50 genes
  app/controllers/site_controller.rb
  app/models/gene.rb
  app/views/layouts/application.html.erb
  app/views/site/_search_options.html.erb
  app/views/site/search/_search_genes.html.erb
  yarn.lock
Labels: security-risk: low

#353 delete cell metadata in bigquery (for SCP-2039 and SCP-2043)
  .gitignore
  .travis.yml
  Gemfile
  Gemfile.lock
  app/controllers/application_controller.rb
  app/controllers/studies_controller.rb
  app/models/delete_queue_job.rb
  bin/load_env_secrets.sh
  bin/run_tests.sh
  config/initializers/delayed_job_config.rb
  test/integration/study_creation_test.rb
  test/integration/study_validation_test.rb
  test/test_data/metadata_example_using_convention.txt
  yarn.lock
Labels: ruby, security-risk: low

#352 Limiting multiple/global gene searches to 50 genes
  app/assets/javascripts/application.js
  app/controllers/site_controller.rb
  app/models/gene.rb
  app/views/layouts/application.html.erb
  app/views/site/_search_options.html.erb
  app/views/site/search/_search_genes.html.erb
Labels: security-risk: low

#357 New Relic monitoring for performance and JS errors (SCP-1902)
  app/views/layouts/_nr_script.js.erb
  app/views/layouts/application.html.erb
  bin/boot_docker
  config/initializers/content_security_policy.rb
  nginx.conf
  yarn.lock
Labels: security-risk: low

#360 Fixing error with 2d cluster domain ranges
  app/views/site/_study_scatter_layout.html.erb
  yarn.lock
Labels: security-risk: low

#361 Release 0.39.1
  app/views/site/_study_scatter_layout.html.erb
  yarn.lock
Labels: security-risk: low

#365 Fixing parse error email contents
  app/models/ingest_job.rb
Labels: dependencies, security-risk: low

#362 Autocomplete bugfixes
  app/assets/javascripts/application.js
  app/views/layouts/application.html.erb
  app/views/site/_search_options.html.erb
  test/integration/study_validation_test.rb
  yarn.lock
Labels: security-risk: low

#363 Bugfixes for deployments re: yarn, subsampling cleanup
  app/models/delete_queue_job.rb
  bin/deploy.sh
Labels: security-risk: low

#369 Separating BigQuery cell_metadata datasets by Rails environment
  app/models/cell_metadatum.rb
  app/models/delete_queue_job.rb
  app/models/papi_client.rb
  test/integration/study_creation_test.rb
  yarn.lock
Labels: security-risk: low

#372 Db react integration
  .gitignore
  NON_CONTAINERIZED_DEV_README.md
  README.md
  app/assets/stylesheets/application.css.scss
  app/javascript/components/ScpSearchStudies.js
  app/javascript/packs/application.js
  app/javascript/styles/_brand.scss
  app/javascript/styles/_global.scss
  app/javascript/styles/_spin.scss
  app/javascript/styles/application.scss
  app/views/layouts/application.html.erb
  app/views/site/index.html.erb
  babel.config.js
  config/environments/development.rb
  config/initializers/content_security_policy.rb
  config/secrets/.keep_this
  config/webpacker.yml
  package.json
  rails_local_setup.rb
  rails_startup.bash
  yarn.lock
Labels: ruby, security-risk: low

#375 Profile, email delivery bug fixes
  app/controllers/profiles_controller.rb
  app/models/parse_utils.rb
Labels: security-risk: low

#376 handle clusters with percent signs (SCP-2110)
  app/views/site/_study_visualize.html.erb
  app/views/site/render_global_gene_expression_plots.js.erb
Labels: security-risk: low

#378 Prototype UI for facets and filters (SCP-2047)
  app/javascript/components/FacetAccordian.js
  app/javascript/components/FacetButton.js
  app/javascript/components/FacetControl.js
  app/javascript/components/FacetsAccordion.js
  app/javascript/components/FacetsAccordionBox.js
  app/javascript/components/FacetsMockData.js
  app/javascript/components/Filters.js
  app/javascript/components/FiltersBox.js
  app/javascript/components/FiltersSearchBar.js
  app/javascript/components/MoreFiltersButton.js
  app/javascript/components/ScpSearchStudies.js
  app/javascript/packs/application.js
  app/javascript/styles/_search.scss
  app/javascript/styles/application.scss
  app/views/site/index.html.erb
  package.json
  yarn.lock
Labels: security-risk: low
