Repository broadinstitute/single_cell_portal_core, pull requests merged in 2022-03, with the labels that each got.

#1400 Update to Ingest Pipeline 1.14.2 (SCP-4139)
  config/application.rb
Labels: build failure: false positive

#1404 Release 1.10.0
  .github/workflows/run-all-tests.yml
  Gemfile.lock
  app/controllers/api/v1/search_controller.rb
  app/javascript/components/search/controls/KeywordSearch.js
  app/javascript/components/upload/FileUploadControl.js
  app/javascript/components/validation/ValidationMessage.js
  app/javascript/lib/validation/chunked-line-reader.js
  app/javascript/lib/validation/io.js
  app/javascript/lib/validation/log-validation.js
  app/javascript/lib/validation/validate-file-content.js
  app/javascript/lib/validation/validate-file.js
  app/javascript/lib/validation/validate-remote-file-content.js
  app/javascript/packs/application.js
  app/javascript/providers/UserProvider.js
  app/models/author.rb
  app/models/study.rb
  app/views/studies/_shared_sync_functions.js.erb
  app/views/studies/sync_study.html.erb
  config/application.rb
  db/migrate/20200221193404_add_bq_organism_age_column.rb
  test/api/search_controller_test.rb
  test/js/lib/validate-file-content.test.js
  test/js/lib/validate-remote-file-content.test.js
  yarn.lock
Labels: build failure: false positive

#1406 Removing auth requirement for XDSS, retiring feature flags (SCP-4163)
  app/controllers/api/v1/search_controller.rb
  app/javascript/components/HomePageContent.js
  app/javascript/components/HomePageContentLegacy.js
  app/models/search_facet.rb
  db/migrate/20220304144348_retire_xdss_feature_flags.rb
  test/api/search_controller_test.rb
  test/models/search_facet_test.rb
Labels: build failure: false positive

#1411 Validate that dense matrices do not have empty values (SCP-4036)
  app/javascript/lib/validation/expression-matrices-validation.js
  test/js/lib/validate-file-content.test.js
Labels: build failure: false positive

#1413 Update sync survey link (off cycle, SCP-4153)
  app/views/studies/sync_study.html.erb
Labels: review exception: hotfix, build failure: false positive

#1405 updating study sidebar and settings UX (SCP-4130)
  app/assets/javascripts/application.js
  app/javascript/lib/InfoPopup.jsx
  app/javascript/styles/_global.scss
  app/javascript/vite/application.js
  app/views/site/_study_description_view.html.erb
  app/views/site/_study_resources_sidebar.html.erb
  app/views/site/_study_settings_form.html.erb
  app/views/studies/show.html.erb
Labels: build failure: false positive

#1421 removing unneeded dev logs/errors (SCP-4172)
  config/environments/development.rb
  config/routes.rb
Labels: build failure: false positive

#1420 improving performance of large data array loading (SCP-3756)
  app/models/concerns/concatenatable.rb
Labels: build failure: false positive

#1424 adding corrupted workspace based on sentry error (SCP-4176)
  lib/study_cleanup_tools.rb
Labels: review exception: hotfix

#1428 Fix security issue in `ansi-html` (SCP-4191)
  package.json
  test/js/download/download-selection-modal.test.js
  test/js/setup-tests.js
  yarn.lock
Labels: build failure: false positive

#1433 fixing auth code analytics capture (SCP-4207)
  app/javascript/lib/scp-api-metrics.js
  app/javascript/lib/scp-api.jsx
  app/views/site/_study_download_data.html.erb
Labels: build failure: false positive

#1434 Update to Ingest Pipeline 1.15.0
  config/application.rb
Labels: build failure: false positive

#1431 Fix security issue in activestorage (SCP-4192)
  Gemfile
  Gemfile.lock
Labels: build failure: false positive

#1435 Fix single-gene Explore view when default annotation is numeric (SCP-4200)
  app/javascript/components/explore/ExploreDisplayTabs.jsx
  app/javascript/components/visualization/PlotDisplayControls.jsx
  app/javascript/components/visualization/StudyViolinPlot.jsx
Labels: build failure: false positive
