Repository broadinstitute/single_cell_portal_core, pull requests merged in 2024-10, with the labels that each got.

#2143 Instant validation for only-alphanumeric-underscore headers (SCP-5790)
  app/javascript/lib/validation/shared-validation.js
  app/javascript/lib/validation/validate-anndata.js
  app/javascript/lib/validation/validate-file-content.js
  test/js/lib/validate-anndata.test.js
  test/js/lib/validate-file-content.test.js
  test/test_data/anndata/invalid_annotation_name_period.h5ad
  test/test_data/metadata_example.txt
  test/test_data/validation/cluster_valid_annotation_name_period.txt
  test/test_data/validation/header_count_mismatch.tsv
  test/test_data/validation/metadata_bad_has_coordinates.txt
  test/test_data/validation/metadata_bad_type_header.txt
  test/test_data/validation/metadata_invalid_annotation_name_period.tsv
Labels: build failure: false positive

#2152 Update filtering tooltip to indicate data is unfiltered (SCP-5819)
  app/javascript/components/explore/ExploreDisplayPanelManager.jsx
Labels: build failure: false positive

#2158 Restore IGV filtering (SCP-5851)
  app/javascript/components/explore/ExploreDisplayTabs.jsx
  test/js/explore/explore-display-tabs.test.js
Labels: build failure: false positive

#2157 Removing unused name-as-id method (SCP-5828)
  app/models/study_file.rb
  app/views/studies/show.html.erb
Labels: build failure: false positive

#2159 Release 1.83.0
  app/controllers/api/v1/study_search_results_objects.rb
  app/javascript/components/explore/ExploreDisplayTabs.jsx
  app/javascript/components/explore/FacetComponents.jsx
  app/javascript/components/search/genes/StudyGeneExpressions.jsx
  app/javascript/components/search/results/ResultMetadataTable.jsx
  app/javascript/components/search/results/StudyResults.jsx
  app/javascript/components/search/results/StudySearchResult.jsx
  app/javascript/lib/sentry-logging.js
  app/javascript/styles/_searchPanel.scss
  app/lib/azul_search_service.rb
  app/models/ann_data_ingest_parameters.rb
  app/models/concerns/compute_scaling.rb
  app/models/delete_queue_job.rb
  app/models/differential_expression_parameters.rb
  app/models/expression_file_info.rb
  app/models/ingest_job.rb
  app/models/study_file.rb
  app/views/studies/show.html.erb
  config/application.rb
  config/initializers/content_security_policy.rb
  package.json
  test/api/search_controller_test.rb
  test/js/explore/explore-display-tabs.test.js
  test/js/search/gene-search-view.test.js
  test/js/search/result-metadata-table.test.js
  test/js/search/study.test.js
  test/js/studyResults.test.js
  test/models/delete_queue_job_test.rb
  test/models/ingest_job_test.rb
  test/models/study_file_test.rb
  test/services/azul_search_service_test.rb
  yarn.lock
Labels: build failure: false positive

#2163 Update to Ingest 1.37.0: Better gene search for CELLxGENE AnnData
  config/application.rb
Labels: build failure: false positive, review exception: deferred

#2164 Release 1.84.0
  Gemfile.lock
  config/application.rb
Labels: review exception: deferred
